version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./receipt_processor:/app/receipt_processor
    command: python manage.py runserver 0.0.0.0:8000
    container_name: ReceiptProcessor
